from normalized_amplitude_temporal_least_squares_windowing import NormalizedAmplitudeWindowedTemporalLeastSquares
from temporal_least_squares_windowing import WindowedTemporalLeastSquares
from temporal_least_squares_ddfwi_norm_then_differences_windowing import TemporalLeastSquaresWindowedDDFWINormUtoDThenDiff